community/urls.py
from django.urls import path
from . import views

app_name = 'community'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/<int:movie_pk>/', views.create, name='create'),
    path('<int:review_pk>/', views.detail, name='detail'),
    path('<int:review_pk>/update/', views.update, name='update'),
    path('<int:review_pk>/comments/create/', views.create_comment, name='create_comment'),
    path('<int:review_pk>/comments/<int:comment_pk>/', views.delete_comment, name='delete_comment'),
    path('<int:review_pk>/like/', views.like, name='like'),
]

final_pjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('community/', include('community.urls')),
    path('accounts/', include('accounts.urls')),
    path('movies/', include('movies.urls')),
    path('guns/', include('guns.urls')),
    path('', include('home.urls')),
]

guns/urls.py
from django.urls import path
from . import views

app_name = 'guns'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:gun_pk>/', views.detail, name='detail'),
    path('<int:gun_pk>/like/', views.like, name='like'),
]

movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:movie_pk>/', views.detail, name='detail'),
    path('<int:movie_pk>/like/', views.like, name='like'),
    path('db/', views.db, name='db'),
    path('moviedb/', views.moviedb, name='moviedb'),
    path('<movie_title>/update/', views.update, name='update'),
]

movies/models.py
from django.db import models
from django.conf import settings
from guns.models import Gun


class Genre(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Movie(models.Model):
    title = models.CharField(max_length=100)
    release_date = models.DateField(null=True, blank=True)
    popularity = models.FloatField(null=True, blank=True)
    vote_count = models.IntegerField(null=True, blank=True)
    vote_average = models.FloatField(null=True, blank=True)
    overview = models.TextField(null=True, blank=True)
    poster_path = models.CharField(max_length=200, null=True, blank=True)
    original_title = models.CharField(max_length=100, null=True, blank=True)
    genres = models.ManyToManyField(Genre, blank=True)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_movies', blank=True)
    related_guns = models.ManyToManyField(Gun, related_name='related_movies', blank=True)

    def __str__(self):
        return self.title

    # class Meta:
    #     ordering = ['title']

movies/forms.py
from django import forms
from .models import Movie


class MovieForm(forms.ModelForm):
    
    class Meta:
        model = Movie
        exclude = ('original_title',)

movies/views.py
from django.shortcuts import get_object_or_404, render, get_list_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_safe, require_POST, require_http_methods
from .models import Movie, Genre
from django.http import JsonResponse
from .forms import MovieForm
import requests
from guns.models import Gun
from bs4 import BeautifulSoup
import math


@require_safe
def index(request):
    search_keyword = request.GET.get('search_keyword')
    search_type = request.GET.get('search_type')
    if search_keyword == 'None' or not search_keyword:
        movies = Movie.objects.all()
    else:
        if search_type == 'search_by_title':
            movies = Movie.objects.filter(title__icontains=search_keyword)
        elif search_type == 'search_by_original_title':
            movies = Movie.objects.filter(original_title__icontains=search_keyword)
        elif search_type == 'search_by_genre':
            movies = Movie.objects.filter(genres__name__icontains=search_keyword)
    typeof = request.GET.get('typeof')
    if typeof == 'None' or not typeof:
        typeof = 'title_asc'
    if typeof == 'title_asc':
        movies = movies.order_by('title')
    elif typeof == 'title_des':
        movies = movies.order_by('-title')
    elif typeof == 'release_date_asc':
        movies = movies.order_by('release_date')
    elif typeof == 'release_date_des':
        movies = movies.order_by('-release_date')
    elif typeof == 'popularity_asc':
        movies = movies.order_by('popularity')
    elif typeof == 'popularity_des':
        movies = movies.order_by('-popularity')
    elif typeof == 'vote_average_asc':
        movies = movies.order_by('vote_average')
    elif typeof == 'vote_average_des':
        movies = movies.order_by('-vote_average')
    elif typeof == 'like_users_asc':
        movies = movies.order_by('like_users')
    elif typeof == 'like_users_des':
        movies = movies.order_by('-like_users')
    pagelist = request.GET.get('pagelist')
    if pagelist == 'None' or not pagelist:
        pagelist = 1
    else:
        pagelist = int(pagelist)
    pagenumbers = [i for i in range(10 * pagelist - 9, 10 * pagelist + 1)]
    page = request.GET.get('page')
    if page=='None' or not page:
        page = 1
    else:
        page = int(page)
    valid_page = math.ceil(len(movies) / 12)
    valid_pages = [i for i in range(1, valid_page + 1)]
    valid_pagelist = math.ceil(valid_page / 10)
    valid_pagelists = [i for i in range(1, valid_pagelist)]
    movies = movies[12 * (page - 1):12 * page]
    context = {
        'movies': movies,
        'typeof': typeof,
        'pagelist': pagelist,
        'pagenumbers': pagenumbers,
        'page': page,
        'search_keyword': search_keyword,
        'search_type': search_type,
        'valid_pages': valid_pages,
        'valid_pagelists' : valid_pagelists,
    }
    return render(request, 'movies/index.html', context)


@require_http_methods(['GET', 'POST'])
def detail(request, movie_pk):
    movie = get_object_or_404(Movie, pk=movie_pk)
    if request.method == 'POST':
        if request.user.is_superuser:
            movie.delete()
            return redirect('movies:index')
        else:
            print('not superuser')
    else:
        context = {
            'movie': movie,
        }
        return render(request, 'movies/detail.html', context)


@require_POST
def like(request, movie_pk):
    if request.user.is_authenticated:
        movie = get_object_or_404(Movie, pk=movie_pk)
        user = request.user

        if movie.like_users.filter(pk=user.pk).exists():
            movie.like_users.remove(user)
            liked = False
        else:
            movie.like_users.add(user)
            liked = True
        count = movie.like_users.count()
        context = {
            'liked': liked,
            'count': count,
        }
        return JsonResponse(context)
    return redirect('accounts:login')


@login_required
@require_http_methods(['GET', 'POST'])
def db(request):
    if request.method == 'POST':
        if request.user.is_superuser:
            form = MovieForm()
            movie = form.save(commit=False)
            movie.title = request.POST.get('title')
            movie.release_date = request.POST.get('release_date')
            movie.popularity = request.POST.get('popularity')
            movie.vote_count = request.POST.get('vote_count')
            movie.vote_average = request.POST.get('vote_average')
            movie.overview = request.POST.get('overview')
            movie.poster_path = request.POST.get('poster_path')
            movie.original_title = request.POST.get('original_title')
            movie.save()
            genre_ids = request.POST.get('genre_ids')
            for genre_id in genre_ids[1:-1].split(', '):
                genre = get_object_or_404(Genre, pk=genre_id)
                movie.genres.add(genre)
            return render(request, 'movies/db.html')
        else:
            print('not superuser')
    else:
        if request.user.is_superuser:
            if request.GET.get('search_keyword'):
                search_keyword = request.GET.get('search_keyword')
                movies = Movie.objects.all()
                movie_titles = []
                for movie in movies:
                    movie_titles.append(movie.title)
                BASE_URL = 'https://api.themoviedb.org/3'
                path = '/search/movie'
                params = {
                    'api_key': '05752707a030a1c74935741bb5d3e4e3',
                    'region': 'KR',
                    'language': 'ko',
                    'query': search_keyword,
                }
                response = requests.get(BASE_URL+path, params=params)
                data = response.json()
                context = {
                    'data': data,
                    'movie_titles': movie_titles,
                }
                return render(request, 'movies/db.html', context)
            else:
                return render(request, 'movies/db.html')
        else:
            print('not superuser')


@login_required
@require_POST
def moviedb(request):
    if request.user.is_superuser:
        guns = Gun.objects.all()
        for gun in guns:
            url = 'http://www.imfdb.org/wiki/' + gun.gun_name
            page = requests.get(url)
            soup = BeautifulSoup(page.text, "html.parser")
            elements = soup.select('span.toctext')
            count = 0
            for element in elements:
                if element.text == 'Film':
                    count += 1
            if count > 1:
                for element in elements:
                    if gun.gun_name == element.text:
                        for span in element.parent.parent.select('span.toctext'):
                            if span.text == 'Film':
                                for tr in soup.select_one('span#' + span.parent['href'][1:]).parent.find_next_sibling('table').select('i > a'):
                                    if Movie.objects.filter(original_title=tr.text).exists():
                                        movies = get_list_or_404(Movie, original_title=tr.text)
                                        for movie in movies:
                                            movie.related_guns.add(gun)
                                    else:
                                        BASE_URL = 'https://api.themoviedb.org/3'
                                        path = '/search/movie'
                                        params = {
                                            'api_key': '05752707a030a1c74935741bb5d3e4e3',
                                            'region': 'KR',
                                            'language': 'ko',
                                            'query': tr.text,
                                        }
                                        response = requests.get(BASE_URL+path, params=params)
                                        data = response.json()
                                        if data['results']:
                                            form = MovieForm()
                                            movie = form.save(commit=False)
                                            movie.title = data['results'][0].get('title')
                                            if data['results'][0].get('release_date'):
                                                movie.release_date = data['results'][0].get('release_date')
                                            if data['results'][0].get('popularity'):
                                                movie.popularity = data['results'][0].get('popularity')
                                            if data['results'][0].get('vote_count'):
                                                movie.vote_count = data['results'][0].get('vote_count')
                                            if data['results'][0].get('vote_average'):
                                                movie.vote_average = data['results'][0].get('vote_average')
                                            if data['results'][0].get('overview'):
                                                movie.overview = data['results'][0].get('overview')
                                            if data['results'][0].get('poster_path'):
                                                movie.poster_path = 'https://image.tmdb.org/t/p/w500' + data['results'][0].get('poster_path')
                                            if data['results'][0].get('original_title'):
                                                movie.original_title = data['results'][0].get('original_title')
                                            movie.save()
                                            genre_ids = data['results'][0]['genre_ids']
                                            for genre_id in genre_ids:

movies/templates/movies/db.html
{% extends 'base.html' %}

{% block content %}
  <h1>DB 채우기</h1>
  <div>
    <div>
      <form action="">
        <p>TMDB 영화 제목
          <input type="text" name="search_keyword"><button>검색</button>
        </p>
      </form>
    </div>
    <div>
      <form action="{% url 'movies:moviedb' %}" method="POST">
        {% csrf_token %}
        <button>전체 DB 갱신</button>
      </form>
    </div>
  </div>
  <hr>
  {% for movie in data.results %}
    <img style='width: 400px;' src="https://image.tmdb.org/t/p/w500{{ movie.poster_path }}" alt="{{ movie.title }}">
    {% if movie.title in movie_titles %}
      <h1 class="text-danger">중복 영화!!</h1>
    {% endif %}
    {% if movie.title not in movie_titles %}
      <form action="" method="POST">
        {% csrf_token %}
    {% endif %}
      <h2>영화 제목: <input type="text" value="{{ movie.title }}" name="title" class="border-0 text-white bg-transparent p-0" size="30" readonly></h2>
      <p>장르 ID: <input type="text" value="{{ movie.genre_ids }}" name="genre_ids" class="border-0 text-white bg-transparent p-0" size="30" readonly></p>
      <p>영화 개봉일: <input type="text" value="{{ movie.release_date }}" name="release_date" class="border-0 text-white bg-transparent p-0" size="30" readonly></p>
      <p>인기도: <input type="text" value="{{ movie.popularity }}" name="popularity" class="border-0 text-white bg-transparent p-0" size="30" readonly></p>
      <p>영화 평점: <input type="text" value="{{ movie.vote_average }}" name="vote_average" class="border-0 text-white bg-transparent p-0" size="30" readonly></p>
      <p>영화 줄거리: <input type="text" value="{{ movie.overview }}" name="overview" class="border-0 text-white bg-transparent p-0" size="200" readonly></p>
      <input type="text" value="{{ movie.vote_count }}" name="vote_count" size="30" hidden>
      <input type="text" value="https://image.tmdb.org/t/p/w500{{ movie.poster_path }}" name="poster_path" size="30" hidden>
      <input type="text" value="{{ movie.original_title }}" name="original_title" hidden>
      {% if movie.title in movie_titles %}
        <a href="{% url 'movies:update' movie.title %}"><button>영화 정보 수정</button></a>
      {% else %}
        <button>영화 DB 등록</button>
      </form>
      {% endif %}
      
    <hr>
  {% endfor %}
{% endblock content %}

movies/templates/movies/detail.html
{% extends 'base.html' %}

{% load static %}

{% block style %}
  <style>
    svg {
      cursor: pointer;
      overflow: visible;
      width: 60px;
    }
    svg #heart {
      transform-origin: center;
      animation: animateHeartOut 0.3s linear forwards;
    }
    svg #main-circ {
      transform-origin: 29.5px 29.5px;
    }

    #checkbox {
      display: none;
    }

    #checkbox:checked + label svg #heart {
      transform: scale(0.2);
      fill: #E2264D;
      animation: animateHeart 0.3s linear forwards 0.25s;
    }
    #checkbox:checked + label svg #main-circ {
      transition: all 2s;
      animation: animateCircle 0.3s linear forwards;
      opacity: 1;
    }
    #checkbox:checked + label svg #grp1 {
      opacity: 1;
      transition: 0.1s all 0.3s;
    }
    #checkbox:checked + label svg #grp1 #oval1 {
      transform: scale(0) translate(0, -30px);
      transform-origin: 0 0 0;
      transition: 0.5s transform 0.3s;
    }
    #checkbox:checked + label svg #grp1 #oval2 {
      transform: scale(0) translate(10px, -50px);
      transform-origin: 0 0 0;
      transition: 1.5s transform 0.3s;
    }
    #checkbox:checked + label svg #grp2 {
      opacity: 1;
      transition: 0.1s all 0.3s;
    }
    #checkbox:checked + label svg #grp2 #oval1 {
      transform: scale(0) translate(30px, -15px);
      transform-origin: 0 0 0;
      transition: 0.5s transform 0.3s;
    }
    #checkbox:checked + label svg #grp2 #oval2 {
      transform: scale(0) translate(60px, -15px);
      transform-origin: 0 0 0;
      transition: 1.5s transform 0.3s;
    }
    #checkbox:checked + label svg #grp3 {
      opacity: 1;
      transition: 0.1s all 0.3s;
    }
    #checkbox:checked + label svg #grp3 #oval1 {
      transform: scale(0) translate(30px, 0px);
      transform-origin: 0 0 0;
      transition: 0.5s transform 0.3s;
    }
    #checkbox:checked + label svg #grp3 #oval2 {
      transform: scale(0) translate(60px, 10px);
      transform-origin: 0 0 0;
      transition: 1.5s transform 0.3s;
    }
    #checkbox:checked + label svg #grp4 {
      opacity: 1;
      transition: 0.1s all 0.3s;
    }
    #checkbox:checked + label svg #grp4 #oval1 {
      transform: scale(0) translate(30px, 15px);
      transform-origin: 0 0 0;
      transition: 0.5s transform 0.3s;
    }
    #checkbox:checked + label svg #grp4 #oval2 {
      transform: scale(0) translate(40px, 50px);
      transform-origin: 0 0 0;
      transition: 1.5s transform 0.3s;
    }
    #checkbox:checked + label svg #grp5 {
      opacity: 1;
      transition: 0.1s all 0.3s;
    }
    #checkbox:checked + label svg #grp5 #oval1 {
      transform: scale(0) translate(-10px, 20px);
      transform-origin: 0 0 0;
      transition: 0.5s transform 0.3s;
    }
    #checkbox:checked + label svg #grp5 #oval2 {
      transform: scale(0) translate(-60px, 30px);
      transform-origin: 0 0 0;
      transition: 1.5s transform 0.3s;
    }
    #checkbox:checked + label svg #grp6 {
      opacity: 1;
      transition: 0.1s all 0.3s;
    }
    #checkbox:checked + label svg #grp6 #oval1 {
      transform: scale(0) translate(-30px, 0px);
      transform-origin: 0 0 0;
      transition: 0.5s transform 0.3s;
    }
    #checkbox:checked + label svg #grp6 #oval2 {
      transform: scale(0) translate(-60px, -5px);
      transform-origin: 0 0 0;
      transition: 1.5s transform 0.3s;
    }
    #checkbox:checked + label svg #grp7 {
      opacity: 1;
      transition: 0.1s all 0.3s;
    }
    #checkbox:checked + label svg #grp7 #oval1 {
      transform: scale(0) translate(-30px, -15px);
      transform-origin: 0 0 0;
      transition: 0.5s transform 0.3s;
    }
    #checkbox:checked + label svg #grp7 #oval2 {
      transform: scale(0) translate(-55px, -30px);
      transform-origin: 0 0 0;
      transition: 1.5s transform 0.3s;
    }
    #checkbox:checked + label svg #grp2 {
      opacity: 1;
      transition: 0.1s opacity 0.3s;
    }
    #checkbox:checked + label svg #grp3 {
      opacity: 1;
      transition: 0.1s opacity 0.3s;
    }
    #checkbox:checked + label svg #grp4 {
      opacity: 1;
      transition: 0.1s opacity 0.3s;
    }
    #checkbox:checked + label svg #grp5 {
      opacity: 1;
      transition: 0.1s opacity 0.3s;
    }
    #checkbox:checked + label svg #grp6 {
      opacity: 1;
      transition: 0.1s opacity 0.3s;
    }
    #checkbox:checked + label svg #grp7 {
      opacity: 1;
      transition: 0.1s opacity 0.3s;
    }

    @keyframes animateCircle {
      40% {
        transform: scale(10);
        opacity: 1;
        fill: #DD4688;
      }
      55% {
        transform: scale(11);
        opacity: 1;
        fill: #D46ABF;
      }
      65% {
        transform: scale(12);
        opacity: 1;
        fill: #CC8EF5;
      }
      75% {
        transform: scale(13);
        opacity: 1;
        fill: transparent;
        stroke: #CC8EF5;
        stroke-width: 0.5;
      }
      85% {
        transform: scale(17);
        opacity: 1;
        fill: transparent;
        stroke: #CC8EF5;
        stroke-width: 0.2;
      }
      95% {
        transform: scale(18);
        opacity: 1;
        fill: transparent;
        stroke: #CC8EF5;
        stroke-width: 0.1;
      }
      100% {
        transform: scale(19);
        opacity: 1;
        fill: transparent;
        stroke: #CC8EF5;
        stroke-width: 0;
      }
    }
    @keyframes animateHeart {
      0% {
        transform: scale(0.2);
      }
      40% {
        transform: scale(1.2);
      }
      100% {
        transform: scale(1);
      }
    }
    @keyframes animateHeartOut {
      0% {
        transform: scale(1.4);
      }
      100% {
        transform: scale(1);
      }
    }

    .inner-border {
      border: solid 0.1em white;
      text-align: center;
    }

    .movie-info {
      border: solid 0.2em white;
      margin-top: 80px;
    }

    .gun-card {
      {% comment %} background-color: transparent; {% endcomment %}
      margin: 0px 15px 15px 15px;
    }

  </style>
{% endblock style %}

{% block content %}
  <div class='movie-info container'>
    <div class='row text-center py-3' style="border-bottom: solid 2px white;">
      <div class='col-8'>
        <h2 style='padding-left: 450px; font-size:1.8rem; padding-top: 10px; margin-bottom: 0px;'>{{ movie.title }}</h2>
      </div>
      <div class='col-4'>
        <div id="main-content" class='col-4 d-flex align-items-center justify-content-center'>
          <div>
            <input type="checkbox" id="checkbox" class="like-{{ movie.pk }}" data-movie-id="{{ movie.pk }}"
            {% if user in movie.like_users.all %}
              checked
            {% endif %}
            />
            <label for="checkbox">
              <svg id="heart-svg" viewBox="467 392 58 57" xmlns="http://www.w3.org/2000/svg">
                <g id="Group" fill="none" fill-rule="evenodd" transform="translate(467 392)">
                  <path d="M29.144 20.773c-.063-.13-4.227-8.67-11.44-2.59C7.63 28.795 28.94 43.256 29.143 43.394c.204-.138 21.513-14.6 11.44-25.213-7.214-6.08-11.377 2.46-11.44 2.59z" id="heart" fill="#AAB8C2"/>
                  <circle id="main-circ" fill="#E2264D" opacity="0" cx="29.5" cy="29.5" r="1.5"/>
        
                  <g id="grp7" opacity="0" transform="translate(7 6)">
                    <circle id="oval1" fill="#9CD8C3" cx="2" cy="6" r="2"/>
                    <circle id="oval2" fill="#8CE8C3" cx="5" cy="2" r="2"/>
                  </g>
        
                  <g id="grp6" opacity="0" transform="translate(0 28)">
                    <circle id="oval1" fill="#CC8EF5" cx="2" cy="7" r="2"/>
                    <circle id="oval2" fill="#91D2FA" cx="3" cy="2" r="2"/>
                  </g>
        
                  <g id="grp3" opacity="0" transform="translate(52 28)">
                    <circle id="oval2" fill="#9CD8C3" cx="2" cy="7" r="2"/>
                    <circle id="oval1" fill="#8CE8C3" cx="4" cy="2" r="2"/>
                  </g>
        
                  <g id="grp2" opacity="0" transform="translate(44 6)">
                    <circle id="oval2" fill="#CC8EF5" cx="5" cy="6" r="2"/>
                    <circle id="oval1" fill="#CC8EF5" cx="2" cy="2" r="2"/>
                  </g>
        
                  <g id="grp5" opacity="0" transform="translate(14 50)">
                    <circle id="oval1" fill="#91D2FA" cx="6" cy="5" r="2"/>
                    <circle id="oval2" fill="#91D2FA" cx="2" cy="2" r="2"/>
                  </g>
        
                  <g id="grp4" opacity="0" transform="translate(35 50)">
                    <circle id="oval1" fill="#F48EA7" cx="6" cy="5" r="2"/>
                    <circle id="oval2" fill="#F48EA7" cx="2" cy="2" r="2"/>
                  </g>
        
                  <g id="grp1" opacity="0" transform="translate(24)">
                    <circle id="oval1" fill="#9FC7FA" cx="2.5" cy="3" r="2"/>
                    <circle id="oval2" fill="#9FC7FA" cx="7.5" cy="2" r="2"/>
                  </g>
                </g>
              </svg>
            </label>
          </div>
          <span id="like-count-{{ movie.pk }}" style='font-size: 30px;'>{{ movie.like_users.all|length }}</span>
        </div>
      </div>
    </div>
    <div class='row my-3'>
      <div class='card-title d-flex justify-content-center'>
        <img style='width: 500px;' src="{{ movie.poster_path }}" alt="{{ movie.title }}">
      </div>
    </div>
    <div class='card-body'>
      <div class='row'>
        <div class='col-4 inner-border'>
          <p style='margin: 10px 0px;'>장르</p>
        </div>
        <div class='col-8 inner-border'>
          <p  style='margin: 10px 0px;'>
            {% for genre in movie.genres.all %}
              {{ genre }}
            {% endfor %}
          </p>
        </div>
      </div>
      <div class='row'>
        <div class='col-4 inner-border'>
          <p style='margin: 10px 0px;'>영화 개봉일</p>
        </div>
        <div class='col-8 inner-border'>
          <p style='margin: 10px 0px;'>{{ movie.release_date }}</p>
        </div>
      </div>
      <div class='row'>
        <div class='col-4 inner-border'>
          <p style='margin: 10px 0px;'>인기도</p>
        </div>
        <div class='col-8 inner-border'>
          <p style='margin: 10px 0px;'>{{ movie.popularity }}</p>
        </div>
      </div>
      <div class='row'>
        <div class='col-4 inner-border'>
          <p style='margin: 10px 0px;'>영화 평점</p>
        </div>
        <div class='col-8 inner-border'>
          <p style='margin: 10px 0px;'>{{ movie.vote_average }}</p>    
        </div>
      </div>
      <div class='row'>
        <div class='col-4 inner-border'>
          <p class='d-flex justify-content-center'>영화 줄거리</p>
        </div>
        <div class='col-8 inner-border'>
          <p style='margin: 10px 0px;'>{{ movie.overview }}</p>
        </div>
      </div>
    </div>
    <div class='container' style='border: solid 2px white; margin-bottom: 20px;'>
      <div class='row d-flex justify-content-center py-3 h2' style='border-bottom: solid 2px white;'>
        {{ movie.title }}에 등장한 총기
      </div>
      <div class='row d-flex justify-content-center'>
          {% for related_gun in movie.related_guns.all %}
          <div class=' gun-card card col-5 d-flex align-items-center'>
            <div class='card-title d-flex align-items-center' style='min-height: 300px; border-bottom: solid 0.1em black;'>
            <img src="{% static related_gun.gun_image_path %}" alt="gun_image">
            </div>
            <div class='card-body'>
              <li class='d-flex justify-content-center'><a href="{% url 'guns:detail' related_gun.pk%}" class=''>{{ related_gun.gun_name }}</a></li>
            </div>
          </div>
          {% endfor %}
      </div>
    </div>
    <div>
      <div class='d-flex justify-content-evenly mb-3'>
        {% if user.is_superuser %}
        <a href="{% url 'movies:update' movie.title %}"><button class='btn btn-success'>영화 정보 수정</button></a>
        {% endif %}
        <a href="{% url 'community:create' movie.pk %}"><button class='btn btn-success'>영화 리뷰 작성</button></a>
        <a href="{% url 'movies:index' %}"><button class='btn btn-primary'>뒤로가기</button></a>
        {% if user.is_superuser %}
          <form action="" method="POST">
            {% csrf_token %}
            <button class='btn btn-danger' onclick="return confirm('정말 삭제하시겠습니까?')">영화 삭제</button>
          </form>
        {% endif %}
      </div>
    </div>  
  </div>

{% endblock %}

{% block script %}
  <script>
    const csrf_token = document.querySelector('[name=csrfmiddlewaretoken]').value
    const likeButton = document.querySelector('#checkbox')
    likeButton.addEventListener('click', function (event) {
      const movieId = event.target.dataset.movieId
      axios({
        method: 'post',
        url: `http://127.0.0.1:8000/movies/${movieId}/like/`,
        headers: {'X-CSRFToken': csrf_token},
      })
      .then(response => {
        const count = response.data.count
        const liked = response.data.liked
        const likeButton = document.querySelector(`.like-${movieId}`)
        const likeCount = document.querySelector(`#like-count-${movieId}`)
        if (liked === true) {
          likeButton.checked = true
        } else {
          likeButton.checked = false
        }
        likeCount.innerText = count
      })
    })
  </script>
{% endblock %}

movies/templates/movies/update.html
{% extends 'base.html' %}

{% block content %}
  <div class="m-3">
    <h1>영화 정보 수정</h1>
    <h2>(CTRL + 클릭으로 다중 선택)</h2>
    <form action="" method="POST">
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit">
    </form>
  </div>
{% endblock content %}