accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('signout/', views.signout, name='signout'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='change_pasword'),
    path('<username>/', views.profile, name='profile'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
]

community/urls.py
from django.urls import path
from . import views

app_name = 'community'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/<int:movie_pk>/', views.create, name='create'),
    path('<int:review_pk>/', views.detail, name='detail'),
    path('<int:review_pk>/update/', views.update, name='update'),
    path('<int:review_pk>/comments/create/', views.create_comment, name='create_comment'),
    path('<int:review_pk>/comments/<int:comment_pk>/', views.delete_comment, name='delete_comment'),
    path('<int:review_pk>/like/', views.like, name='like'),
]

final_pjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('community/', include('community.urls')),
    path('accounts/', include('accounts.urls')),
    path('movies/', include('movies.urls')),
    path('guns/', include('guns.urls')),
    path('', include('home.urls')),
]

guns/urls.py
from django.urls import path
from . import views

app_name = 'guns'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:gun_pk>/', views.detail, name='detail'),
    path('<int:gun_pk>/like/', views.like, name='like'),
]

movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:movie_pk>/', views.detail, name='detail'),
    path('<int:movie_pk>/like/', views.like, name='like'),
    path('db/', views.db, name='db'),
    path('moviedb/', views.moviedb, name='moviedb'),
    path('<movie_title>/update/', views.update, name='update'),
]

community/models.py
from django.db import models
from django.conf import settings
from movies.models import Movie

class Review(models.Model):
    title = models.CharField(max_length=100)
    rank = models.FloatField()
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    movie_title = models.ForeignKey(Movie, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_reviews')

    def __str__(self):
        return self.title


class Comment(models.Model):
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    review = models.ForeignKey(Review, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

community/forms.py
from tkinter import Widget
from django import forms
from .models import Review, Comment


class ReviewForm(forms.ModelForm):
    rank = forms.FloatField(
        min_value=0,
        max_value=5,
        widget=forms.NumberInput(
            attrs={
                'step': 0.5,
                'style': 'width: 75px; height: 29px;'
            }
        )
    )

    class Meta:
        model = Review
        fields = ['title', 'rank', 'content',]
        widgets = {
            'title': forms.TextInput(
                attrs={
                    'style': 'width: 634px; height: 29px;',
                }
            ),
            'content': forms.Textarea(
                attrs={
                    'style': 'width: 634px; height: 283px; resize: none;',
                }
            )
        }
        

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        exclude = ['review', 'user',]
        widgets = {
            'content': forms.Textarea(
                attrs={
                    'style': 'width: 500px; height: 120px; resize: none;',
                    'placeholder': '내용을 작성해주세요.',
                }
            )
        }

community/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_GET, require_POST, require_http_methods
from .models import Review, Comment
from .forms import ReviewForm, CommentForm
from django.http import JsonResponse
from movies.models import Movie
from django.contrib.auth.decorators import login_required
import math


@require_GET
def index(request):
    search_keyword = request.GET.get('search_keyword')
    search_type = request.GET.get('search_type')
    typeof = request.GET.get('typeof')
    if typeof == 'None' or not typeof:
        typeof = 'created_at_des'
    page = request.GET.get('page')
    if page=='None' or not page:
        page = 1
    else:
        page = int(page)
    reviews_or_comments = request.GET.get('reviews_or_comments')
    if reviews_or_comments == 'None' or not reviews_or_comments:
        reviews_or_comments = 'reviews'
    if reviews_or_comments == 'reviews':
        reviews = Review.objects.all()
        if search_keyword == 'None' or not search_keyword:
            pass
        else:
            if search_type == 'search_by_review_title':
                reviews = reviews.filter(title__icontains=search_keyword)
            elif search_type == 'search_by_review_content':
                reviews = reviews.filter(content__icontains=search_keyword)
            elif search_type == 'search_by_review_user':
                reviews = reviews.filter(user__username__icontains=search_keyword)
            elif search_type == 'search_by_movie_title':
                reviews = reviews.filter(movie_title__title__icontains=search_keyword)
        if typeof == 'created_at_asc':
            reviews = reviews.order_by('created_at')
        elif typeof == 'created_at_des':
            reviews = reviews.order_by('-created_at')
        elif typeof == 'rank_asc':
            reviews = reviews.order_by('rank')
        elif typeof == 'rank_des':
            reviews = reviews.order_by('-rank')
        elif typeof == 'like_users_asc':
            reviews = reviews.order_by('-like_users')
        elif typeof == 'like_users_des':
            reviews = reviews.order_by('-like_users')
        valid_page = math.ceil(len(reviews) / 15)
        reviews = reviews[15 * (page - 1):15 * page]
    elif reviews_or_comments == 'comments':
        comments = Comment.objects.all()
        if search_keyword == 'None' or not search_keyword:
            pass
        else:
            if request.GET.get('search_type') == 'search_by_comment_content':
                comments = comments.filter(content__icontains=search_keyword)
            elif request.GET.get('search_type') == 'search_by_comment_user':
                comments = comments.filter(user__username__icontains=search_keyword)
        if typeof == 'created_at_asc':
            comments = comments.order_by('created_at')
        elif typeof == 'created_at_des':
            comments = comments.order_by('-created_at')
        valid_page = math.ceil(len(comments) / 15)
        comments = comments[15 * (page - 1):15 * page]
    pagelist = request.GET.get('pagelist')
    if pagelist == 'None' or not pagelist:
        pagelist = 1
    else:
        pagelist = int(pagelist)
    pagenumbers = [i for i in range(10 * pagelist - 9, 10 * pagelist + 1)]
    valid_pages = [i for i in range(1, valid_page + 1)]
    valid_pagelist = math.ceil(valid_page / 10)
    valid_pagelists = [i for i in range(1, valid_pagelist)]
    if reviews_or_comments == 'reviews':
        context = {
            'reviews': reviews,
            'typeof': typeof,
            'pagelist': pagelist,
            'pagenumbers': pagenumbers,
            'page': page,
            'search_keyword': search_keyword,
            'search_type': search_type,
            'valid_pages': valid_pages,
            'valid_pagelists' : valid_pagelists,
            'reviews_or_comments' : reviews_or_comments,
        }
    elif reviews_or_comments == 'comments':
        context = {
            'comments': comments,
            'typeof': typeof,
            'pagelist': pagelist,
            'pagenumbers': pagenumbers,
            'page': page,
            'search_keyword': search_keyword,
            'search_type': search_type,
            'valid_pages': valid_pages,
            'valid_pagelists' : valid_pagelists,
            'reviews_or_comments' : reviews_or_comments,
        }
    return render(request, 'community/index.html', context)


@login_required
@require_http_methods(['GET', 'POST'])
def create(request, movie_pk):
    movie = get_object_or_404(Movie, pk=movie_pk)
    if request.method == 'POST':
        form = ReviewForm(request.POST) 
        if form.is_valid():
            review = form.save(commit=False)
            review.user = request.user
            review.movie_title = movie
            review.save()
            return redirect('community:detail', review.pk)
    else:
        form = ReviewForm()
    context = {
        'form': form,
        'movie': movie,
    }
    return render(request, 'community/create.html', context)


@require_http_methods(['GET', 'POST'])
def detail(request, review_pk):
    review = get_object_or_404(Review, pk=review_pk)
    if request.method == 'POST':
        if review.user == request.user:
            review.delete()
            return redirect('community:index')
        return redirect('community:detail')
    else:
        comments = review.comment_set.all()
        comment_form = CommentForm()
        context = {
            'review': review,
            'comment_form': comment_form,
            'comments': comments,
        }
        return render(request, 'community/detail.html', context)


@require_http_methods(['GET', 'POST'])
def update(request, review_pk):
    review = get_object_or_404(Review, pk=review_pk)
    movie = get_object_or_404(Movie, pk=review.movie_title.pk)
    if review.user == request.user:
        if request.method == 'POST':
            form = ReviewForm(request.POST, instance=review) 
            if form.is_valid():
                review = form.save()
                return redirect('community:detail', review.pk)          
        else:
            form = ReviewForm(instance=review)
    else:
        return redirect('community:detail', review.pk)
    context = {
        'form': form,
        'review': review,
        'movie': movie,
    }
    return render(request, 'community/update.html', context)
    
    
@require_POST
def create_comment(request, review_pk):
    review = get_object_or_404(Review, pk=review_pk)
    comment_form = CommentForm(request.POST)
    if comment_form.is_valid():
        comment = comment_form.save(commit=False)
        comment.review = review
        comment.user = request.user
        comment.save()
        return redirect('community:detail', review.pk)
    context = {
        'comment_form': comment_form,
        'review': review,
        'comments': review.comment_set.all(),
    }
    return render(request, 'community/detail.html', context)


@require_POST
def delete_comment(request, review_pk, comment_pk):
    comment = get_object_or_404(Comment, pk=comment_pk)
    if comment.user == request.user:
        comment.delete()
    return redirect('community:detail', review_pk)


@require_POST
def like(request, review_pk):
    if request.user.is_authenticated:
        review = get_object_or_404(Review, pk=review_pk)
        user = request.user

        if review.like_users.filter(pk=user.pk).exists():
            review.like_users.remove(user)
            liked = False
        else:
            review.like_users.add(user)
            liked = True
        count = review.like_users.count()
        context = {
            'liked': liked,
            'count': count,
        }
        return JsonResponse(context)
    return redirect('accounts:login')

community/templates/community/create.html
{% extends 'base.html' %}

{% block content %}
  <div class="m-3">
    <h1 class="text-center">리뷰 작성</h1>
    <div>
      <form action="" method="POST">
        {% csrf_token %}
        <table class="table bg-white mx-auto mb-0" style="height: 0px; width: 750px;">
          <thead style="background-color: #323D3F;">
            <tr>
              <th scope="col" style="border: 0; width: 100px;"></th>
              <th scope="col" style="border: 0;"></th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <th scope="row" colspan="2" class="text-center" style="background-color: #323D3F; border: 0;"><img src="{{ movie.poster_path }}" alt="{{ moviee.title }}" style="width: 300px;"></th>
            </tr>
            <tr>
              <th scope="row" class="text-center bg-dark text-white" style="border: 0;">리뷰 제목</th>
              <td>{{ form.title }}</td>
            </tr>
            <tr>
              <th scope="row" class="text-center bg-dark text-white" style="border: 0;">영화 제목</th>
              <td>{{ movie.title }}</td>
            </tr>
            <tr>
              <th scope="row" class="text-center bg-dark text-white" style="border: 0;">리뷰 평점</th>
              <td>{{ form.rank }}</td>
            </tr>
            <tr>
              <th scope="row" class="text-center bg-dark text-white" style="border: 0;">리뷰 내용</th>
              <td style="height: 300px;">{{ form.content }}</td>
            </tr>
            <tr>
              <th scope="row" class="bg-dark" style="border: 0;"></th>
              <td class="d-flex justify-content-end"><button class="btn btn-success">등록</button></td>
            </tr>
          </tbody>
        </table>
      </form>
    </div>
    <hr>
    <a href="{% url 'movies:detail' movie.pk %}"><button class="btn btn-primary">뒤로가기</button></a>
  </div>
{% endblock %}

community/templates/community/detail.html
{% extends 'base.html' %}

{% block style %}
  <style>
    svg {
      cursor: pointer;
      overflow: visible;
      width: 25px;
    }
    svg #heart {
      transform-origin: center;
      animation: animateHeartOut 0.3s linear forwards;
    }
    svg #main-circ {
      transform-origin: 29.5px 29.5px;
    }

    .checkbox {
      display: none;
    }

    .checkbox:checked + label svg #heart {
      transform: scale(0.2);
      fill: #E2264D;
      animation: animateHeart 0.3s linear forwards 0.25s;
    }
    .checkbox:checked + label svg #main-circ {
      transition: all 2s;
      animation: animateCircle 0.3s linear forwards;
      opacity: 1;
    }
    .checkbox:checked + label svg #grp1 {
      opacity: 1;
      transition: 0.1s all 0.3s;
    }
    .checkbox:checked + label svg #grp1 #oval1 {
      transform: scale(0) translate(0, -30px);
      transform-origin: 0 0 0;
      transition: 0.5s transform 0.3s;
    }
    .checkbox:checked + label svg #grp1 #oval2 {
      transform: scale(0) translate(10px, -50px);
      transform-origin: 0 0 0;
      transition: 1.5s transform 0.3s;
    }
    .checkbox:checked + label svg #grp2 {
      opacity: 1;
      transition: 0.1s all 0.3s;
    }
    .checkbox:checked + label svg #grp2 #oval1 {
      transform: scale(0) translate(30px, -15px);
      transform-origin: 0 0 0;
      transition: 0.5s transform 0.3s;
    }
    .checkbox:checked + label svg #grp2 #oval2 {
      transform: scale(0) translate(60px, -15px);
      transform-origin: 0 0 0;
      transition: 1.5s transform 0.3s;
    }
    .checkbox:checked + label svg #grp3 {
      opacity: 1;
      transition: 0.1s all 0.3s;
    }
    .checkbox:checked + label svg #grp3 #oval1 {
      transform: scale(0) translate(30px, 0px);
      transform-origin: 0 0 0;
      transition: 0.5s transform 0.3s;
    }
    .checkbox:checked + label svg #grp3 #oval2 {
      transform: scale(0) translate(60px, 10px);
      transform-origin: 0 0 0;
      transition: 1.5s transform 0.3s;
    }
    .checkbox:checked + label svg #grp4 {
      opacity: 1;
      transition: 0.1s all 0.3s;
    }
    .checkbox:checked + label svg #grp4 #oval1 {
      transform: scale(0) translate(30px, 15px);
      transform-origin: 0 0 0;
      transition: 0.5s transform 0.3s;
    }
    .checkbox:checked + label svg #grp4 #oval2 {
      transform: scale(0) translate(40px, 50px);
      transform-origin: 0 0 0;
      transition: 1.5s transform 0.3s;
    }
    .checkbox:checked + label svg #grp5 {
      opacity: 1;
      transition: 0.1s all 0.3s;
    }
    .checkbox:checked + label svg #grp5 #oval1 {
      transform: scale(0) translate(-10px, 20px);
      transform-origin: 0 0 0;
      transition: 0.5s transform 0.3s;
    }
    .checkbox:checked + label svg #grp5 #oval2 {
      transform: scale(0) translate(-60px, 30px);
      transform-origin: 0 0 0;
      transition: 1.5s transform 0.3s;
    }
    .checkbox:checked + label svg #grp6 {
      opacity: 1;
      transition: 0.1s all 0.3s;
    }
    .checkbox:checked + label svg #grp6 #oval1 {
      transform: scale(0) translate(-30px, 0px);
      transform-origin: 0 0 0;
      transition: 0.5s transform 0.3s;
    }
    .checkbox:checked + label svg #grp6 #oval2 {
      transform: scale(0) translate(-60px, -5px);
      transform-origin: 0 0 0;
      transition: 1.5s transform 0.3s;
    }
    .checkbox:checked + label svg #grp7 {
      opacity: 1;
      transition: 0.1s all 0.3s;
    }
    .checkbox:checked + label svg #grp7 #oval1 {
      transform: scale(0) translate(-30px, -15px);
      transform-origin: 0 0 0;
      transition: 0.5s transform 0.3s;
    }
    .checkbox:checked + label svg #grp7 #oval2 {
      transform: scale(0) translate(-55px, -30px);
      transform-origin: 0 0 0;
      transition: 1.5s transform 0.3s;
    }
    .checkbox:checked + label svg #grp2 {
      opacity: 1;
      transition: 0.1s opacity 0.3s;
    }
    .checkbox:checked + label svg #grp3 {
      opacity: 1;
      transition: 0.1s opacity 0.3s;
    }
    .checkbox:checked + label svg #grp4 {
      opacity: 1;
      transition: 0.1s opacity 0.3s;
    }
    .checkbox:checked + label svg #grp5 {
      opacity: 1;
      transition: 0.1s opacity 0.3s;
    }
    .checkbox:checked + label svg #grp6 {
      opacity: 1;
      transition: 0.1s opacity 0.3s;
    }
    .checkbox:checked + label svg #grp7 {
      opacity: 1;
      transition: 0.1s opacity 0.3s;
    }

    @keyframes animateCircle {
      40% {
        transform: scale(10);
        opacity: 1;
        fill: #DD4688;
      }
      55% {
        transform: scale(11);
        opacity: 1;
        fill: #D46ABF;
      }
      65% {
        transform: scale(12);
        opacity: 1;
        fill: #CC8EF5;
      }
      75% {
        transform: scale(13);
        opacity: 1;
        fill: transparent;
        stroke: #CC8EF5;
        stroke-width: 0.5;
      }
      85% {
        transform: scale(17);
        opacity: 1;
        fill: transparent;
        stroke: #CC8EF5;
        stroke-width: 0.2;
      }
      95% {
        transform: scale(18);
        opacity: 1;
        fill: transparent;
        stroke: #CC8EF5;
        stroke-width: 0.1;
      }
      100% {
        transform: scale(19);
        opacity: 1;
        fill: transparent;
        stroke: #CC8EF5;
        stroke-width: 0;
      }
    }
    @keyframes animateHeart {
      0% {
        transform: scale(0.2);
      }
      40% {
        transform: scale(1.2);
      }
      100% {
        transform: scale(1);
      }
    }
    @keyframes animateHeartOut {
      0% {
        transform: scale(1.4);
      }
      100% {
        transform: scale(1);
      }
    }
  </style>
{% endblock style %}

{% block content %}
  <div class="m-3">
    <div>
      <table class="table bg-white mx-auto mb-0" style="height: 0px; width: 750px;">
        <thead style="background-color: #323D3F;">
          <tr>
            <th scope="col" style="border: 0; width: 100px;"></th>
            <th scope="col" style="border: 0;"></th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <th scope="row" colspan="2" class="text-center" style="background-color: #323D3F; border: 0;"><img src="{{ review.movie_title.poster_path }}" alt="{{ review.movie_title.title }}" style="width: 300px;"></th>
          </tr>
          <tr>
            <th scope="row" class="text-center bg-dark text-white" style="border: 0;">리뷰 제목</th>
            <td>{{ review.title }}</td>
          </tr>
          <tr>
            <th scope="row" class="text-center bg-dark text-white" style="border: 0;">영화 제목</th>
            <td><a href="{% url 'movies:detail' review.movie_title.pk %}" class="text-dark">{{ review.movie_title }}</a></td>
          </tr>
          <tr>
            <th scope="row" class="text-center bg-dark text-white" style="border: 0;">리뷰 평점</th>
            <td>{{ review.rank }}</td>
          </tr>
          <tr>
            <th scope="row" class="text-center bg-dark text-white" style="border: 0;">작성일</th>
            <td>{{ review.created_at }}</td>
          </tr>
          <tr>
            <th scope="row" class="text-center bg-dark text-white" style="border: 0;">작성자</th>
            <td><a href="{% url 'accounts:profile' review.user.username %}" class="text-dark">{{ review.user.username }}</a></td>
          </tr>
          <tr>
            <th scope="row" class="text-center bg-dark text-white" style="border: 0;">좋아요</th>
            <td>
              <div class="d-flex align-items-center">
                <div id="main-content">
                  <div>
                    <input type="checkbox" id="checkbox-{{ review.pk }}" class="checkbox" data-review-id="{{ review.pk }}"
                    {% if user in review.like_users.all %}
                      checked
                    {% endif %}
                    />
                    <label for="checkbox-{{ review.pk }}">
                      <svg id="heart-svg" viewBox="467 392 58 57" xmlns="http://www.w3.org/2000/svg">
                        <g id="Group" fill="none" fill-rule="evenodd" transform="translate(467 392)">
                          <path d="M29.144 20.773c-.063-.13-4.227-8.67-11.44-2.59C7.63 28.795 28.94 43.256 29.143 43.394c.204-.138 21.513-14.6 11.44-25.213-7.214-6.08-11.377 2.46-11.44 2.59z" id="heart" fill="#AAB8C2"/>
                          <circle id="main-circ" fill="#E2264D" opacity="0" cx="29.5" cy="29.5" r="1.5"/>
                
                          <g id="grp7" opacity="0" transform="translate(7 6)">
                            <circle id="oval1" fill="#9CD8C3" cx="2" cy="6" r="2"/>
                            <circle id="oval2" fill="#8CE8C3" cx="5" cy="2" r="2"/>
                          </g>
                
                          <g id="grp6" opacity="0" transform="translate(0 28)">
                            <circle id="oval1" fill="#CC8EF5" cx="2" cy="7" r="2"/>
                            <circle id="oval2" fill="#91D2FA" cx="3" cy="2" r="2"/>
                          </g>
                
                          <g id="grp3" opacity="0" transform="translate(52 28)">
                            <circle id="oval2" fill="#9CD8C3" cx="2" cy="7" r="2"/>
                            <circle id="oval1" fill="#8CE8C3" cx="4" cy="2" r="2"/>
                          </g>
                
                          <g id="grp2" opacity="0" transform="translate(44 6)">
                            <circle id="oval2" fill="#CC8EF5" cx="5" cy="6" r="2"/>
                            <circle id="oval1" fill="#CC8EF5" cx="2" cy="2" r="2"/>
                          </g>
                
                          <g id="grp5" opacity="0" transform="translate(14 50)">
                            <circle id="oval1" fill="#91D2FA" cx="6" cy="5" r="2"/>
                            <circle id="oval2" fill="#91D2FA" cx="2" cy="2" r="2"/>
                          </g>
                
                          <g id="grp4" opacity="0" transform="translate(35 50)">
                            <circle id="oval1" fill="#F48EA7" cx="6" cy="5" r="2"/>
                            <circle id="oval2" fill="#F48EA7" cx="2" cy="2" r="2"/>
                          </g>
                
                          <g id="grp1" opacity="0" transform="translate(24)">
                            <circle id="oval1" fill="#9FC7FA" cx="2.5" cy="3" r="2"/>
                            <circle id="oval2" fill="#9FC7FA" cx="7.5" cy="2" r="2"/>
                          </g>
                        </g>
                      </svg>
                    </label>
                  </div>
                </div>
                <span id="like-count-{{ review.pk }}">{{ review.like_users.all|length }}</span>
              </div>
            </td>
          </tr>
          <tr>
            <th scope="row" class="text-center bg-dark text-white" style="border: 0;">리뷰 내용</th>
            <td style="height: 300px; display: block; overflow: auto;">{{ review.content }}</td>
          </tr>
          {% if review.user == request.user %}
            <tr>
              <th scope="row" class="text-center bg-dark" style="border: 0;"></th>
              <td style="border: 0;">
                <div class="d-flex justify-content-end">
                  <a href="{% url 'community:update' review.pk %}"><button class="btn btn-success">리뷰 수정</button></a>
                  <form action="" method="POST" class="mx-3">
                    {% csrf_token %}
                    <button class="btn btn-success">리뷰 삭제</button>
                  </form>
                </div>
              </td>
            </tr>
          {% endif %}
        </tbody>
      </table>
    </div>
    
    <hr>
    <h4>댓글 ({{ comments|length }})</h4>
    {% for comment in comments %}
      <div class="d-flex my-1">
        <span style="font-size: 20px;"><a href="{% url 'accounts:profile' comment.user.username %}" class="text-white">{{ comment.user }}</a> : {{ comment.content }}</span>
        {% if comment.user == request.user %}
          <form action="{% url 'community:delete_comment' review.pk comment.pk %}" method="POST" class="mx-2">
            {% csrf_token %}  
            <button class="btn btn-light" style="font-size: 12px;">삭제</button>
          </form>
        {% endif %}
      </div>
    {% empty %}
      <p>첫 댓글을 작성해주세요!</p>
    {% endfor %}
    <hr>
    {% if request.user.is_authenticated %}
      <form action="{% url 'community:create_comment' review.pk %}" method="POST" class="d-flex">
        {% csrf_token %}
        <div>
          <p>댓글 : </p>
        </div>
        <div>
          {{ comment_form.content }}
        </div>
        <div class="d-flex align-items-end">
          <button class="btn btn-light mx-2" style="font-size: 15px;">등록</button>
        </div>
      </form>
    {% else %}
      <a href="{% url 'accounts:login' %}">[댓글을 작성하려면 로그인하세요.]</a>
    {% endif %}
    <a href="{% url 'community:index' %}"><button class="btn btn-primary my-2">뒤로가기</button></a>
  </div>
{% endblock  %}

{% block script %}
<script>
  const checkbox = document.querySelector('.checkbox')
  const csrf_token = document.querySelector('[name=csrfmiddlewaretoken]').value
  checkbox.addEventListener('click', function (event) {
    event.preventDefault()
    const reviewId = event.target.dataset.reviewId
    axios({
      method: 'post',
      url: `http://127.0.0.1:8000/community/${reviewId}/like/`,
      headers: {'X-CSRFToken': csrf_token},
    })
    .then(response => {
      const count = response.data.count
      const liked = response.data.liked
      const likeButton = document.querySelector(`#checkbox-${reviewId}`)
      const likeCount = document.querySelector(`#like-count-${reviewId}`)
      if (liked === true) {
        likeButton.checked = true
      } else {
        likeButton.checked = false
      }
      likeCount.innerText = count
    })
  })
  </script>
{% endblock %}

community/templates/community/update.html
{% extends 'base.html' %}

{% block content %}
  <div class="m-3">
    <h1 class="text-center">리뷰 수정</h1>
    <div>
      <form action="" method="POST">
        {% csrf_token %}
        <table class="table bg-white mx-auto mb-0" style="height: 0px; width: 750px;">
          <thead style="background-color: #323D3F;">
            <tr>
              <th scope="col" style="border: 0; width: 100px;"></th>
              <th scope="col" style="border: 0;"></th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <th scope="row" colspan="2" class="text-center" style="background-color: #323D3F; border: 0;"><img src="{{ movie.poster_path }}" alt="{{ moviee.title }}" style="width: 300px;"></th>
            </tr>
            <tr>
              <th scope="row" class="text-center bg-dark text-white" style="border: 0;">리뷰 제목</th>
              <td>{{ form.title }}</td>
            </tr>
            <tr>
              <th scope="row" class="text-center bg-dark text-white" style="border: 0;">영화 제목</th>
              <td>{{ movie.title }}</td>
            </tr>
            <tr>
              <th scope="row" class="text-center bg-dark text-white" style="border: 0;">리뷰 평점</th>
              <td>{{ form.rank }}</td>
            </tr>
            <tr>
              <th scope="row" class="text-center bg-dark text-white" style="border: 0;">리뷰 내용</th>
              <td style="height: 300px;" id="textarea">{{ form.content }}</td>
            </tr>
            <tr>
              <th scope="row" class="bg-dark" style="border: 0;"></th>
              <td class="d-flex justify-content-end"><button class="btn btn-success">등록</button></td>
            </tr>
          </tbody>
        </table>
      </form>
    </div>
    <hr>
    <a href="{% url 'community:detail' review.pk %}"><button class="btn btn-primary">뒤로가기</button></a>
  </div>
{% endblock %}