accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('signout/', views.signout, name='signout'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='change_pasword'),
    path('<username>/', views.profile, name='profile'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
]

community/urls.py
from django.urls import path
from . import views

app_name = 'community'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/<int:movie_pk>/', views.create, name='create'),
    path('<int:review_pk>/', views.detail, name='detail'),
    path('<int:review_pk>/update/', views.update, name='update'),
    path('<int:review_pk>/comments/create/', views.create_comment, name='create_comment'),
    path('<int:review_pk>/comments/<int:comment_pk>/', views.delete_comment, name='delete_comment'),
    path('<int:review_pk>/like/', views.like, name='like'),
]

final_pjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('community/', include('community.urls')),
    path('accounts/', include('accounts.urls')),
    path('movies/', include('movies.urls')),
    path('guns/', include('guns.urls')),
    path('', include('home.urls')),
]

guns/urls.py
from django.urls import path
from . import views

app_name = 'guns'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:gun_pk>/', views.detail, name='detail'),
    path('<int:gun_pk>/like/', views.like, name='like'),
]

movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:movie_pk>/', views.detail, name='detail'),
    path('<int:movie_pk>/like/', views.like, name='like'),
    path('db/', views.db, name='db'),
    path('moviedb/', views.moviedb, name='moviedb'),
    path('<movie_title>/update/', views.update, name='update'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    followings = models.ManyToManyField('self', symmetrical=False, related_name='followers')

community/models.py
from django.db import models
from django.conf import settings
from movies.models import Movie

class Review(models.Model):
    title = models.CharField(max_length=100)
    rank = models.FloatField()
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    movie_title = models.ForeignKey(Movie, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_reviews')

    def __str__(self):
        return self.title


class Comment(models.Model):
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    review = models.ForeignKey(Review, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth import get_user_model


class CustomUserCreationForm(UserCreationForm):
    
    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = UserCreationForm.Meta.fields


class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = get_user_model()
        fields = ('first_name', 'last_name',)

accounts/views.py
from django.http import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import get_user_model, update_session_auth_hash
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST, require_http_methods
from .forms import CustomUserCreationForm, CustomUserChangeForm
from django.contrib.auth.hashers import check_password


@require_http_methods(['GET', 'POST'])
def signup(request):
    if request.user.is_authenticated:
        return redirect('home:main')

    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():               
            user = form.save()
            auth_login(request, user)
            return redirect('home:main')
    else:
        form = CustomUserCreationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/signup.html', context)


@login_required
@require_http_methods(['GET', 'POST'])
def signout(request):
    if request.method == 'POST':
        password = request.POST.get('password')
        user = request.user
        if check_password(password, user.password):
            user.username = '*deleted_user' + str(user.pk)
            user.save()
            auth_logout(request)
            return redirect('accounts:login')
    return render(request, 'accounts/signout.html')


@require_http_methods(['GET', 'POST'])
def login(request):
    if request.user.is_authenticated:
        return redirect('home:main')

    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect(request.GET.get('next') or 'home:main')
    else:
        form = AuthenticationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/login.html', context)


@require_POST
def logout(request):
    auth_logout(request)
    return redirect('home:main')


@login_required
@require_http_methods(['GET', 'POST'])
def update(request):
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('movies:index')
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {
        'form': form,
    }
    return render(request, 'accounts/update.html', context)


@login_required
@require_http_methods(['GET', 'POST'])
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('movies:index')
    else:
        form = PasswordChangeForm(request.user)
    context = {
        'form': form,
    }
    return render(request, 'accounts/change_password.html', context)


@login_required
def profile(request, username):
    person = get_object_or_404(get_user_model(), username=username)
    context = {
        'person': person,
    }
    return render(request, 'accounts/profile.html', context)


@require_POST
def follow(request, user_pk):
    if request.user.is_authenticated:
        person = get_object_or_404(get_user_model(), pk=user_pk)
        user = request.user
        if person != user:
            if person.followers.filter(pk=user.pk).exists():
                person.followers.remove(user)
                followed = False
            else:
                person.followers.add(user)
                followed = True
            context = {
                'followed': followed,
                'count': person.followers.count(),
            }
        return JsonResponse(context)
    return redirect('accounts:profile', person.username)

accounts/templates/accounts/change_password.html
{% extends 'base.html' %}

{% block content %}
<h1>비밀번호 수정</h1>
<form action="" method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit">
</form>
{% endblock  %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
  <div style='margin-top: 150px;' class='container d-flex justify-content-center'>
    <div style='width: 500px; height: 280px; border: solid 0.2em white;'  class='row d-flex align-content-center'>
      
      <h1 class='col-12 d-block text-center'>로그인</h1>
      
      <div class='d-flex justify-content-center'>
        <form action="" method="POST">
          {% csrf_token %}
          <div>
            {{ form.username.label }}
            <p>{{ form.username }}</p>
            
            {{ form.password.label }}
            <p>{{ form.password }}</p>
            <div class='d-flex justify-content-center'>
              <input type="submit" style='width: 60px; height: 35px;'>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock  %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}

{% block style %}
  <style>
    h2 {
      text-align: center;
      border: solid 0.2em white;
    }

    li {
      color: white;
    }

    a {
      text-decoration: none;
      color: white;
    }

    .ul-div {
      min-height: 300px;
      border: solid 0.15em white;
    }
  </style>


{% endblock style %}

{% block content %}
  <div class='container mt-5'>
    <div class='row'>
      <div class='col-8 d-flex justify-content-between'>
        <h1 class="mx-3">{{ person.username }}님의 프로필 페이지</h1>
        {% with followings=person.followings.all followers=person.followers.all %}
        <div>
          <div class='d-flex justify-content-between'>
            <div class='d-flex justify-content-between'>
              <span>팔로잉 : {{ followings|length }}</span><span>/</span> 팔로워 : <span id="follow-count">{{ followers|length }}</span>
            </div>
            {% if request.user != person %}
              <div>
                <form id="follow-form" action="{% url 'accounts:follow' person.pk %}" method="POST" data-person-id="{{ person.pk }}">
                  {% csrf_token %}
                  {% if request.user in followers %}
                    <button id="followBtn">언팔로우</button>
                  {% else %}
                    <button id="followBtn">팔로우</button>
                  {% endif %}
                </form>
              </div>
            {% endif %}
          </div>
          <div>
            가입일 : {{ user.date_joined }}
          </div>
        </div>
      </div>
      <div class='col-4 d-flex justify-content-end align-items-center'>
        <a href="{% url 'accounts:update' %}"><button>회원정보 수정</button></a>
        <a href="{% url 'accounts:signout' %}"><button>회원 탈퇴</button></a>
      </div>
    </div>
  </div>
  <div class='container mt-4'>
    <div class='row'>
      <div class='col-4'>
        <h2>좋아요한 영화 ({{ user.like_movies.all|length }})</h2>
        <div class='ul-div card-body'>
          <ul>
            {% for movie in user.like_movies.all %}
              <li><a href="{% url 'movies:detail' movie.pk %}">{{ movie.title }}</li></a>
            {% endfor %}
          </ul>
        </div>
      </div>
      
      <div class='col-4'>
        <h2>좋아요한 총 ({{ user.like_guns.all|length }})</h2>
        <div class='ul-div card-body'>
          <ul>
            {% for gun in user.like_guns.all %}
              <li><a href="{% url 'guns:detail' gun.pk %}">{{ gun.gun_name }}</li></a>
            {% endfor %}
          </ul>
        </div>
      </div>
      <div class='col-4'>
        <h2>좋아요한 리뷰 ({{ user.like_reviews.all|length }})</h2>
        <div class='ul-div card-body'>
          <ul>
            {% for review in user.like_reviews.all %}
              <li><a href="{% url 'community:detail' review.pk %}">{{ review.title }}</li></a>
            {% endfor %}
          </ul>
        </div>
      </div>
    </div>
    <div class='row'>
      <div class='col-6'>
        <h2>작성한 리뷰 ({{ user.review_set.all|length }})</h2>
        <div class='ul-div card-body'>
          <ul>
            {% for review in user.review_set.all %}
              <li><a href="{% url 'community:detail' review.pk %}">{{ review.title }}</li></a>
            {% endfor %}
          </ul>
        </div>
      </div>
      <div class='col-6'>
        <h2>작성한 댓글 ({{ user.comment_set.all|length }})</h2>
        <div class='ul-div card-body'>
          <ul>
            {% for comment in user.comment_set.all %}
              <li><a href="{% url 'community:detail' comment.review.pk %}">{{ comment.content|truncatechars:20}}...</li></a>
            {% endfor %}
          </ul>
        </div>
      </div>
    </div>
  </div>
    
  {% endwith %}
{% endblock %}

{% block script %}
  <script>
    const form = document.querySelector('#follow-form')
    const csrf_token = document.querySelector('[name=csrfmiddlewaretoken]').value
    form.addEventListener('submit', function(event) {
      event.preventDefault()
      const personId = event.target.dataset.personId
      axios({
        method: 'post',
        url: `http://127.0.0.1:8000/accounts/${personId}/follow/`,
        headers: {'X-CSRFToken': csrf_token},
      })
      .then(response => {
        const count = response.data.count
        const followed = response.data.followed
        const followButton = document.querySelector('#followBtn')
        const followCount = document.querySelector('#follow-count')
        if (followed === true) {
          followButton.innerText = '언팔로우'
        } else {
          followButton.innerText = '팔로우'
        }
        followCount.innerText = count
      })
    })
  </script>
{% endblock %}

accounts/templates/accounts/signout.html
{% extends 'base.html' %}

{% block content %}
  <div class="mx-3">
    <h1>회원탈퇴</h1>
    <form action="" method="POST">
      {% csrf_token %}
      <p>비밀번호 확인: </p>
      <input type="password" name="password">
      <input type="submit">
    </form>
  </div>
{% endblock  %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block content %}
  <div style='margin-top: 100px;'>
    <div class="container mr-0 p-0 d-flex justify-content-center">
      <div class='row d-flex align-content-between' style='width: 800px; height: 500px; border: solid 0.2em white;' >
        <div class="p-0 mx-3">
          <h1 class='col-12 d-block text-center my-5'>회원가입</h1>
          <form action="" method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <div class='d-flex justify-content-center'>
              <input type="submit" style='width: 60px; height: 35px; margin-top: 20px;'>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock  %}

accounts/templates/accounts/update.html
{% extends 'base.html' %}

{% block content %}
  <div class="mx-3">
    <h1>회원정보 수정</h1>
    <form action="" method="POST">
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit">
    </form>
  </div>
{% endblock  %}