accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('signout/', views.signout, name='signout'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='change_pasword'),
    path('<username>/', views.profile, name='profile'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
]

community/urls.py
from django.urls import path
from . import views

app_name = 'community'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/<int:movie_pk>/', views.create, name='create'),
    path('<int:review_pk>/', views.detail, name='detail'),
    path('<int:review_pk>/update/', views.update, name='update'),
    path('<int:review_pk>/comments/create/', views.create_comment, name='create_comment'),
    path('<int:review_pk>/comments/<int:comment_pk>/', views.delete_comment, name='delete_comment'),
    path('<int:review_pk>/like/', views.like, name='like'),
]

final_pjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('community/', include('community.urls')),
    path('accounts/', include('accounts.urls')),
    path('movies/', include('movies.urls')),
    path('guns/', include('guns.urls')),
    path('', include('home.urls')),
]

guns/urls.py
from django.urls import path
from . import views

app_name = 'guns'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:gun_pk>/', views.detail, name='detail'),
    path('<int:gun_pk>/like/', views.like, name='like'),
]

movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:movie_pk>/', views.detail, name='detail'),
    path('<int:movie_pk>/like/', views.like, name='like'),
    path('db/', views.db, name='db'),
    path('moviedb/', views.moviedb, name='moviedb'),
    path('<movie_title>/update/', views.update, name='update'),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
  <link rel="stylesheet" href="https://unpkg.com/flickity@2/dist/flickity.min.css">
  <title>Guns & Movies</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@500&display=swap" rel="stylesheet">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Ubuntu:wght@300&display=swap" rel="stylesheet">
  <script src="lodash.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/lodash.js/4.17.21/lodash.min.js"></script>
  {% block style %}
  {% endblock style %}
</head>
<body class="text-white" style="background-color: #323D3F; font-family: 'Noto Sans KR', sans-serif;">
  <div>
    <nav class="sticky-top d-flex justify-content-between align-items-center" style="background-color: #141819; height: 80px;">
      <div class="mx-3" style="width: 400px;">
        {% if user.is_authenticated %}
          <a href="{% url 'accounts:profile' user.username %}"><img src="{% static 'accounts/profile_img.jpeg' %}" alt="profile_img" style='width: 40px; margin-right: 5px; border-radius: 50%;'></a>
          <a href="{% url 'accounts:profile' user.username %}" class="text-white" style='text-decoration-line: underline;'>{{ user.username }}</a>님, 안녕하세요!
          {% if user.is_superuser %}
            <a href="{% url 'movies:db' %}" class="text-decoration-none text-white mx-3">DB 채우기</a>
          {% endif %}
        {% else %}
          <a href="{% url 'accounts:signup' %}" class="text-decoration-none text-white">Signup</a>
        {% endif %}
      </div>
      <div id="main_div">
        <h1 class='mb-0'>Guns & Movies</h1>
      </div>
      <div class="d-flex justify-content-evenly" style="width: 400px;">
        {% if user.is_authenticated %}
          <form id="logout_form" action="{% url 'accounts:logout' %}" method="POST">
            {% csrf_token %}
            <div id="logout_div">Logout</div>
          </form>
        
        {% else %}
          <a href="{% url 'accounts:login' %}" class="text-decoration-none text-white">Login</a>
        
        {% endif %}
        <a href="{% url 'guns:index' %}" class="text-decoration-none text-white">Gun</a>
        <a href="{% url 'movies:index' %}" class="text-decoration-none text-white">Movie</a>
        <a href="{% url 'community:index'%}" class="text-decoration-none text-white">Review</a>
        
      </div>
    </nav>
    {% block content %}
    {% endblock %}
  </div>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
  <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
  <script src="https://unpkg.com/flickity@2/dist/flickity.pkgd.min.js"></script>
  <script>
    const mainDiv = document.querySelector('#main_div')
    const logoutDiv = document.querySelector('#logout_div')
    mainDiv.addEventListener('click', function () {
      window.location.href = "http://127.0.0.1:8000/main/"
    })
    logoutDiv.addEventListener('click', function () {
      const form = document.getElementById('logout_form')
      form.submit()
    })
  </script>

  {% block script %}
  {% endblock script %}

  <style>
    #main_div, #logout_div:hover {
      cursor: pointer;
    }
  </style>
</body>
</html>